/*
 * JasperReports - Free Java Reporting Library.
 * Copyright (C) 2001 - 2025 Cloud Software Group, Inc. All rights reserved.
 * http://www.jaspersoft.com
 *
 * Unless you have purchased a commercial license agreement from Jaspersoft,
 * the following license terms apply:
 *
 * This program is part of JasperReports.
 *
 * JasperReports is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JasperReports is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with JasperReports. If not, see <http://www.gnu.org/licenses/>.
 */
package net.sf.jasperreports.export.type;

import net.sf.jasperreports.engine.type.EnumUtil;
import net.sf.jasperreports.engine.type.NamedEnum;
import net.sf.jasperreports.export.AccessibilityUtil;


/**
 * Enumerates the accessibility roles that can be assigned to a report element, for the
 * benefit of exporters that produce accessible output (tagged PDF, accessible HTML
 * tables, accessible PPTX tables).
 * <p/>
 * The role is not carried by a dedicated attribute on the element, but by the generic,
 * element-scoped {@link AccessibilityUtil#PROPERTY_ACCESSIBILITY_TAG} property, whose
 * value is one of the {@link #getName() names} declared here. Report authors can set
 * this property directly in JRXML on any element; in addition, the fill process sets it
 * automatically on the print elements generated by some built-in components, so that
 * the resulting {@link net.sf.jasperreports.engine.JasperPrint} keeps a record of which
 * printed elements make up a table, a table header cell, or a purely decorative
 * artifact, without the exporters having to rediscover that structure from geometry
 * alone.
 * <p/>
 * Not every exporter interprets every value below; each constant documents which
 * exporters currently act on it.
 *
 * @author Teodor Danciu (teodord@users.sourceforge.net)
 */
public enum AccessibilityTagEnum implements NamedEnum
{
	/**
	 * Marks an element (typically a frame) as the root of a data table, so that it is
	 * exported as an actual table structure instead of a plain container.
	 * <p/>
	 * Set automatically by the fill process on the frame that wraps a table component
	 * ({@link net.sf.jasperreports.components.table.fill.FillTable}) or a crosstab
	 * ({@link net.sf.jasperreports.engine.fill.JRFillCrosstab}). Read by the HTML
	 * exporter (via {@link net.sf.jasperreports.engine.export.tabulator.Tabulator}) and
	 * by the PPTX exporter ({@link net.sf.jasperreports.engine.export.ooxml.JRPptxExporter})
	 * to decide whether a frame should be rendered as a nested HTML/PPTX table.
	 */
	TABLE("table"),

	/**
	 * Marks an element (typically a frame) as a table used purely for visual layout,
	 * with no tabular data semantics. Like {@link #TABLE}, it causes a nested table
	 * structure to be generated, but that table is additionally flagged as
	 * presentational (for instance {@code role="none"} in HTML), so that assistive
	 * technology does not announce it as a data table.
	 * <p/>
	 * Set automatically by the fill process on the internal layout frame of the icon
	 * label component ({@link net.sf.jasperreports.components.iconlabel.IconLabelComponentFill}).
	 * Read by the same exporters as {@link #TABLE}.
	 */
	TABLE_LAYOUT("table_layout"),

	/**
	 * Marks an element as a column header cell inside a table structure.
	 * <p/>
	 * Set automatically by the fill process on the elements of a table component's
	 * column header cells ({@link net.sf.jasperreports.components.table.fill.TableReport}).
	 * Read by the HTML exporter (via {@link net.sf.jasperreports.engine.export.tabulator.Tabulator})
	 * to render the cell as a <code>&lt;th&gt;</code> instead of a <code>&lt;td&gt;</code>.
	 */
	COLUMN_HEADER("columnheader"),

	/**
	 * Marks an element as a row header cell inside a table structure. Interpreted the
	 * same way as {@link #COLUMN_HEADER}, but for row headers.
	 * <p/>
	 * Unlike {@link #COLUMN_HEADER}, nothing in the engine currently sets this value
	 * automatically during fill; it is meant to be set explicitly by report authors on
	 * table designs that have row headers.
	 */
	ROW_HEADER("rowheader"),

	/**
	 * Marks a text element, or a frame grouping several text elements, as a level 1
	 * heading. This value is not set by any built-in component; report authors set it
	 * explicitly, as a JRXML element property, on the text elements that should read as
	 * headings.
	 * <p/>
	 * Read by the HTML exporter, which wraps the element's content in a real
	 * <code>&lt;h1&gt;</code> tag. It is also the documented replacement for the older,
	 * PDF-specific {@code net.sf.jasperreports.export.pdf.tag.h1} property (see
	 * {@link net.sf.jasperreports.pdf.common.PdfTagger#PROPERTY_TAG_H1}), for engines
	 * that support tagged PDF heading structures.
	 */
	H1("h1"),

	/**
	 * Level 2 heading; see {@link #H1}.
	 */
	H2("h2"),

	/**
	 * Level 3 heading; see {@link #H1}.
	 */
	H3("h3"),

	/**
	 * Level 4 heading; see {@link #H1}.
	 */
	H4("h4"),

	/**
	 * Level 5 heading; see {@link #H1}.
	 */
	H5("h5"),

	/**
	 * Level 6 heading; see {@link #H1}.
	 */
	H6("h6"),

	/**
	 * Marks an element as a pure visual artifact that carries no informational content,
	 * so that it can be skipped by assistive technology instead of being announced as
	 * meaningful content or read out character by character.
	 * <p/>
	 * Set automatically by the fill process on the private-use-area glyph text field
	 * generated by the icon label component
	 * ({@link net.sf.jasperreports.components.iconlabel.IconLabelComponentUtil}), whose
	 * text is a decorative icon rather than readable content.
	 */
	ARTIFACT("artifact"),

	/**
	 * Marks an element as a reference mark: a small piece of content, typically a
	 * footnote or endnote marker, that points to a {@link #NOTE} located elsewhere in
	 * the document rather than being part of the normal reading flow.
	 * <p/>
	 * This is the documented replacement for the older, PDF-specific
	 * {@code net.sf.jasperreports.export.pdf.tag.reference} property (see
	 * {@link net.sf.jasperreports.pdf.common.PdfTagger#PROPERTY_TAG_REFERENCE}), the
	 * same way {@link #H1} replaces {@code tag.h1}. As with the heading values, no
	 * exporter in this codebase currently reads this value back from
	 * {@link AccessibilityUtil#PROPERTY_ACCESSIBILITY_TAG}; producing the corresponding
	 * tagged-PDF structure is left to PDF producer implementations that support it.
	 */
	REFERENCE("reference"),

	/**
	 * Marks an element as the body of a footnote or endnote, pointed to by one or more
	 * {@link #REFERENCE} elements elsewhere in the document.
	 * <p/>
	 * This is the documented replacement for the older, PDF-specific
	 * {@code net.sf.jasperreports.export.pdf.tag.note} property (see
	 * {@link net.sf.jasperreports.pdf.common.PdfTagger#PROPERTY_TAG_NOTE}). As with
	 * {@link #REFERENCE}, no exporter in this codebase currently reads this value.
	 */
	NOTE("note");

	/**
	 *
	 */
	private final transient String name;

	private AccessibilityTagEnum(String name)
	{
		this.name = name;
	}
	
	@Override
	public String getName()
	{
		return name;
	}
	
	/**
	 *
	 */
	public static AccessibilityTagEnum getByName(String name)
	{
		return EnumUtil.getEnumByName(values(), name);
	}
}
