# loads/override properties from default.jasperreports.properties
net.sf.jasperreports.default.pdf.font.name=liberation/LiberationSans-Regular.ttf
net.sf.jasperreports.default.pdf.embedded=true

net.sf.jasperreports.export.pdf.tagger.factory=net.sf.jasperreports.pdf.common.SilentPdfTaggerFactory
